name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: clone
        run: mkdir downloads
      - name: clone
        run: touch downloads/zlib-1.2.11.1-motley.tar.gz
      - name: clone
        run: git clone https://github.com/madler/zlib.git --branch develop downloads/1.2.11.1-motley
      - name: run build_zlib
        run: ANDROID_NDK=$ANDROID_NDK_HOME ./build_zlib --zlib-version 1.2.11.1-motley
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts.zip
          path: output
