name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: run build_zlib
        run: ANDROID_NDK=$ANDROID_NDK_HOME ./build_zlib
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts.zip
          path: output
